from train import estimate_price, normalize


def load_weights(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()
        # Convert strings to floats
        theta0 = float(lines[0].strip())
        theta1 = float(lines[1].strip())
        mi = float(lines[2].strip())
        ma = float(lines[3].strip())
    return theta0, theta1, mi, ma


def main():
    # Load the weights generated by Program 2
    try:
        theta0, theta1,mi,ma = load_weights('thetas')
    except FileNotFoundError:
        print("Error: Could not find 'thetas' it will be set to 0 . Please run 'train.py' first.")
        theta0=0
        theta1=0
        mi=0
        ma=1
    print(f"Loaded Model weights: {theta0} + ({theta1})")
    
    try:
        user_mileage = float(input("Enter the car mileage (km): "))
        predicted_price = estimate_price(normalize(user_mileage,mi,ma), theta0, theta1)
        print(f"Estimated Price: ${predicted_price:,.2f}")
    except ValueError:
        print("Please enter a valid number.")

if __name__ == "__main__":
    main()